#!/bin/bash
# gimmie_rhel7 v1 created 25 June 2019 
# By Joel Savitz <jsavitz@redhat.com>
#
# Purpose: Get that rhel7 with ease and smoothness


DIRNAME="rhel7_latest"
GITFLAGS="-c http.sslVerify=false"
REPOURL="git://git.app.eng.bos.redhat.com/rhel7"

if [ ! -z $1 ]; then
	DESTINATION=$1
else
	DESTINATION=~
fi

DESTINATION="$DESTINATION/$DIRNAME"

if [ ! -z $2 ]; then
	echo "Usage: $0 [DESTINATION]"
fi

if [ ! -d "$DESTINATION" ]
then
	git $GITFLAGS clone $REPOURL "$DESTINATION"
else
	cd "$DESTINATION"
	git $GITFLAGS pull origin master
fi

ret=$?

exit $ret
