#!/bin/bash
# gimmie_upstream v1 created 08 April 2019 
# By Joel Savitz <jsavitz@redhat.com>
#
# Purpose: Put the latest upstream linux in the home directory

# v1.1 update 17 April 2019
# - make destination dir a variable


DESTINATION="$HOME/upstream_latest"

if [ ! -d "$DESTINATION" ]
then
	git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git "$DESTINATION"
else
	cd "$DESTINATION"
	git pull origin master
fi

ret=$?

exit $ret
