#!/bin/bash
# gimmie_rhel8 v1.1 created 17 April 2019 
# By Joel Savitz <jsavitz@redhat.com>
#
# Purpose: Put the latest rhel8 kernel in the home directory
# v1.1: add ability to set custom destination dir (25 June 2019)

DIRNAME="rhel8_latest"
GITFLAGS="-c http.sslVerify=false"
REPOURL="https://code.engineering.redhat.com/gerrit/kernel-rhel"

if [ ! -z $1 ]; then
	DESTINATION=$1
else
	DESTINATION=~
fi

DESTINATION="$DESTINATION/$DIRNAME"

if [ ! -z $2 ]; then
	echo "Usage: $0 [DESTINATION]"
fi

if [ ! -d "$DESTINATION" ]
then
	git $GITFLAGS clone $REPOURL "$DESTINATION"
else
	cd "$DESTINATION"
	git $GITFLAGS pull origin master
fi

ret=$?

exit $ret
